version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: adminpass
    volumes:
      - ../postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend/
    image: rga-backend
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "3001:3001"
    network_mode: "host"

# volumes:
#   rga-db:
#     driver: local
