version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
      ./postgres/.env
    volumes:
      - rga-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    image: rga-backend
    container_name: rga-backend
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "3001:3001"
    network_mode: "host"

volumes:
  rga-db:
